define(["jquery"], function($) {
    var QuizEngine = {
        // helper functions
        Helpers: {
            stringFormat: function() {
                if(arguments.length > 0) {
                    if(arguments.length === 1) return arguments[0]; // if only 1 argument, return it

                    var stringTemplate = arguments[0]; // first argument is the pattern
                    var args = Array.prototype.slice.call(arguments, 1); // slice the rest of the argument as values

                    // iterate throug the values and match {i} in pattern to replace
                    for(var i = 0; i < args.length; i++) {
                        var regex = new RegExp("\\{" + i + "\\}", "gi");
                        stringTemplate = stringTemplate.replace(regex, args[i]);
                    }

                    return stringTemplate;
                }
                return ""; // if no arguments, return empty string
            },

            displayMsgInDiv: function(options) {
                // set up variables from argument
                var displayDivId = options.displayDivId;
                var message = options.message;
                var setDisplayTo = options.setDisplayTo;
                var displayClasses = options.displayClasses; // array of classes 

                // set up DOM element
                var displayDiv = $(QuizEngine.Helpers.stringFormat("#{0}", displayDivId));

                if(setDisplayTo) displayDiv.css("display", setDisplayTo);
                if(displayClasses) {
                    for(var i = 0; i < displayClasses.length; i++) {
                        displayDiv.addClass(displayClasses[i]);
                    }
                }
                displayDiv.html(message);
            },

            clearMsgDiv: function(options) {
                // set up variables from argument
                var displayDivId = options.displayDivId;
                var setDisplayTo = options.setDisplayTo;
                var displayClasses = options.displayClasses; // array of classes

                // set up DOM element
                var displayDiv = $(QuizEngine.Helpers.stringFormat("#{0}", displayDivId));

                if(setDisplayTo) display.css("display", setDisplayTo);
                if(displayClasses) {
                    for(var i = 0; i < displayClasses.length; i++) {
                        displayDiv.removeClass(displayClasses[i]);
                    }
                }
                displayDiv.empty();
            }
        },


        // widgets
        Widgets: {
            textAreaCharCountdown: function(options) {
                // set up variables from argument
                var formId = options.formId;
                var textAreaId = options.textAreaId;
                var displayDivId = options.displayDivId;
                var maxLength = options.maxLength;
                var placeholderMsg = options.placeholderMsg;
                var neutralPattn = options.neutralPattn;
                var warningPattn = options.warningPattn;
                var warningClasses = options.warningClasses;

                // set up message patterns
                if(!neutralPattn) neutralPattn = "{0}";
                if(!warningPattn) warningPattn = "{0}";

                // set up DOM elements
                var form = $(QuizEngine.Helpers.stringFormat("#{0}", formId));
                // using combo id because form elements generated by htmlhelper may have conflict id's,
                // and overwriting their id's can introduct unexpected results for client side validation, etc.
                var textArea = $(QuizEngine.Helpers.stringFormat("#{0} #{1}", formId, textAreaId));
                var displayDiv = $(QuizEngine.Helpers.stringFormat("#{0} #{1}", formId, displayDivId));

                // set up classes helper functions
                var addClasses = function() {
                    if(warningClasses) {
                        for(var i = 0; i < warningClasses.length; i++) {
                            displayDiv.addClass(warningClasses[i]);
                        }
                    }
                }

                var removeClasses = function() {
                    if(warningClasses) {
                        for(var i = 0; i < warningClasses.length; i++) {
                            displayDiv.removeClass(warningClasses[i]);
                        }
                    }
                }

                // set up reset function
                var resetDisplayDiv = function() {
                    removeClasses();
                    if(placeholderMsg) displayDiv.html(placeholderMsg);
                }

                // set up char counting function
                var countCharsInTextArea = function() {
                    var length = textArea.val().length;
                    var currentCount = maxLength - length;

                    // no input - display placeholder
                    if(currentCount === maxLength) {
                        resetDisplayDiv();
                    }
                    // within max input - display neutral count
                    if(currentCount >= 0 && currentCount < maxLength) {
                        removeClasses();
                        displayDiv.html(QuizEngine.Helpers.stringFormat(neutralPattn, currentCount));
                    }
                    // over max input - display warning count
                    if(currentCount < 0) {
                        addClasses();
                        currentCount = currentCount * -1; // flip negative count
                        displayDiv.html(QuizEngine.Helpers.stringFormat(warningPattn, currentCount));
                    }
                };

                countCharsInTextArea(); // call char counting function as init

                // bind events
                textArea.keyup(countCharsInTextArea);
                form.on("reset", resetDisplayDiv);
            }
        }
    }

    return QuizEngine;
});